imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
#        form:
#            resources:

    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        google_map_key: "%google_map_key%"
        locale: "%locale%"
    form_themes:
        - bootstrap_3_layout.html.twig
        - 'DependentFormsBundle:Form:fields.html.twig'
        - "Form/fields.html.twig"
        - 'Form/vich_fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
            engine: InnoDB
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# ewz_recaptcha
ewz_recaptcha:
    public_key:  %google_recapatcha_site_key%
    private_key: %google_recapatcha_secret_key%
    locale_key:  %kernel.default_locale%

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: '%robot_email%'
        sender_name: '%sender_name%'
    registration:
        form:
            type: UserBundle\Form\RegistrationType
        confirmation:
            enabled: true
            template: '%kernel.root_dir%/Resources/FOSUserBundle/views/Email/confirmation.email.twig'
    resetting:
        form:
            type: UserBundle\Form\ResettingType
        email:
            template: '%kernel.root_dir%/Resources/FOSUserBundle/views/Email/password_resetting.email.twig'
    profile:
        form:
            type: UserBundle\Form\ProfileType

dependent_forms:
    dependent_forms:
        city_by_department:
            class: AppBundle\Entity\locality\City
            parent_property: department
            property: adminName
#            role: ROLE_USER
            no_result_msg: 'Pas de ville trouvée pour ce département'
            order_property: adminName
            order_direction: ASC

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: :Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

vich_uploader:
    db_driver: orm
    mappings:
        observation_image:
            uri_prefix:         /uploads
            upload_destination: %kernel.root_dir%/../web/uploads/
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/../web
                cache_prefix: media/cache

    filter_sets:
        cache: ~
        my_thumb:
            quality: 90
            filters:
                thumbnail: { size: [120, 90], mode: outbound }