<?php

namespace OC\CoreBundle\Repository;

/**
 * NewMdpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewMdpRepository extends \Doctrine\ORM\EntityRepository
{
}
