<?php

namespace OC\CoreBundle\Repository;

/**
 * RechercheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RechercheRepository extends \Doctrine\ORM\EntityRepository
{
}
