services:
    simple_filter_list_entity.form.type.simple_filter:
        class: SimpleFilterListEntityBundle\Form\Type\FilterListType
        arguments: ['@property_accessor']
        tags:
            - { name: form.type, alias: filter_list}