services:
    simple_filter_list_entity.form.type:
        class: SimpleFilterListEntityBundle\Form\Type\SimpleFilterType
        arguments: ['@property_accessor']
        tags:
            - { name: form.type}