app_homepage:
    path:     /
    defaults: { _controller:AppBundle:Main:index }

app_association:
    path:    /association
    defaults: {_controller: AppBundle:Main:association}

app_detailRecherche:
    path:    /detailRecherche
    defaults: {_controller: AppBundle:Main:detailRecherche}

app_contact:
    path:    /contact
    defaults: {_controller: AppBundle:Main:contact}

app_mentions:
    path:    /mentions
    defaults: {_controller: AppBundle:Main:mentions}


app_observations:
    resource: "@AppBundle/Controller/ObservationController.php"
    type:     annotation

app_observations_treatment:
    resource: "@AppBundle/Controller/ObservationTreatmentController.php"
    type:     annotation

app_observations_validation:
    resource: "@AppBundle/Controller/ObservationValidationController.php"
    type:     annotation

