app_homepage:
    path:     /
    defaults: { _controller:AppBundle:Main:index }

app_association:
    path:    /association
    defaults: {_controller: AppBundle:Main:association}

app_recherche:
    path:    /recherche
    defaults: {_controller: AppBundle:Main:recherche}

app_detailRecherche:
    path:    /detailRecherche
    defaults: {_controller: AppBundle:Main:detailRecherche}

app_contact:
    path:    /contact
    defaults: {_controller: AppBundle:Main:contact}

app_mentions:
    path:    /mentions
    defaults: {_controller: AppBundle:Main:mentions}

#app_saisie:
#    path:    /saisie
#    defaults: {_controller: AppBundle:Main:saisie}

#app_observations:
#    path:    /observations
#    defaults: {_controller: AppBundle:Main:observations}

app_validations:
    path:    /validations
    defaults: {_controller: AppBundle:Main:validations}

app_detailValidation:
    path:    /detailValidation
    defaults: {_controller: AppBundle:Main:detailValidation}

app_observations:
    resource: "@AppBundle/Controller/ObservationController.php"
    type:     annotation



