oc_core_homepage:
    path:     /
    defaults: { _controller: OCCoreBundle:Default:index }

oc_core_association:
    path:    /association
    defaults: {_controller: OCCoreBundle:Default:association}

oc_core_recherche:
    path:    /recherche
    defaults: {_controller: OCCoreBundle:Default:recherche}

oc_core_rechercheBis:
    path:    /rechercheBis
    defaults: {_controller: OCCoreBundle:Default:rechercheBis}

oc_core_contact:
    path:    /contact
    defaults: {_controller: OCCoreBundle:Default:contact}

oc_core_inscription:
    path:    /inscription
    defaults: {_controller: OCCoreBundle:Default:inscription}

oc_core_connexion:
    path:    /connexion
    defaults: {_controller: OCCoreBundle:Default:connexion}

oc_core_mdpoublie:
    path:    /motdepasse
    defaults: {_controller: OCCoreBundle:Default:mdpoublie}

oc_core_newmdp:
    path:    /nouveaumotdepasse
    defaults: {_controller: OCCoreBundle:Default:newmdp}

oc_core_mentions:
    path:    /mentions
    defaults: {_controller: OCCoreBundle:Default:mentions}

oc_core_saisie:
    path:    /saisie
    defaults: {_controller: OCCoreBundle:Default:saisie}

oc_core_observations:
    path:    /observations
    defaults: {_controller: OCCoreBundle:Default:observations}



