oc_core_homepage:
    path:     /
    defaults: { _controller: OCCoreBundle:Main:index }

oc_core_association:
    path:    /association
    defaults: {_controller: OCCoreBundle:Main:association}

oc_core_recherche:
    path:    /recherche
    defaults: {_controller: OCCoreBundle:Main:recherche}

oc_core_detailRecherche:
    path:    /detailRecherche
    defaults: {_controller: OCCoreBundle:Main:detailRecherche}

oc_core_contact:
    path:    /contact
    defaults: {_controller: OCCoreBundle:Main:contact}

oc_core_mentions:
    path:    /mentions
    defaults: {_controller: OCCoreBundle:Main:mentions}

oc_core_saisie:
    path:    /saisie
    defaults: {_controller: OCCoreBundle:Main:saisie}

oc_core_observations:
    path:    /observations
    defaults: {_controller: OCCoreBundle:Main:observations}

oc_core_validations:
    path:    /validations
    defaults: {_controller: OCCoreBundle:Main:validations}

oc_core_detailValidation:
    path:    /detailValidation
    defaults: {_controller: OCCoreBundle:Main:detailValidation}



